"""initial_schema

Revision ID: bac1d49c3480
Revises: 
Create Date: 2026-02-28 19:59:46.286219

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel

revision: str = 'bac1d49c3480'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coaches',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
                    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
                    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
                    sa.Column('bio', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
                    sa.Column('tier', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
                    sa.Column('max_clients', sa.Integer(), nullable=False),
                    sa.Column('current_client_count', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email')
                    )
    op.create_table('members',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
                    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
                    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
                    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
                    sa.Column('fitness_level', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
                    sa.Column('membership_tier', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
                    sa.Column('membership_valid_until', sa.Date(), nullable=False),
                    sa.Column('active_plan_id', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email')
                    )
    op.create_table('training_plans',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('member_id', sa.Integer(), nullable=False),
                    sa.Column('coach_id', sa.Integer(), nullable=False),
                    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
                    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
                    sa.Column('starts_at', sa.Date(), nullable=False),
                    sa.Column('ends_at', sa.Date(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('availability_slots',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('coach_id', sa.Integer(), nullable=False),
                    sa.Column('day', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
                    sa.Column('start_hour', sa.Integer(), nullable=False),
                    sa.Column('end_hour', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['coach_id'], ['coaches.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('certifications',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('coach_id', sa.Integer(), nullable=False),
                    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
                    sa.Column('issuing_body', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
                    sa.Column('issued_at', sa.Date(), nullable=False),
                    sa.Column('expires_at', sa.Date(), nullable=True),
                    sa.ForeignKeyConstraint(['coach_id'], ['coaches.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('coach_spec_rows',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('coach_id', sa.Integer(), nullable=False),
                    sa.Column('specialization', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
                    sa.ForeignKeyConstraint(['coach_id'], ['coaches.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('fitness_goals',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('member_id', sa.Integer(), nullable=False),
                    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
                    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
                    sa.Column('target_date', sa.Date(), nullable=False),
                    sa.Column('achieved', sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('workout_sessions',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('plan_id', sa.Integer(), nullable=False),
                    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
                    sa.Column('scheduled_date', sa.Date(), nullable=False),
                    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
                    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.ForeignKeyConstraint(['plan_id'], ['training_plans.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('planned_exercises',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('session_id', sa.Integer(), nullable=False),
                    sa.Column('exercise_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
                    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
                    sa.Column('sets', sa.Integer(), nullable=False),
                    sa.Column('reps', sa.Integer(), nullable=False),
                    sa.Column('rest_seconds', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['session_id'], ['workout_sessions.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planned_exercises')
    op.drop_table('workout_sessions')
    op.drop_table('fitness_goals')
    op.drop_table('coach_spec_rows')
    op.drop_table('certifications')
    op.drop_table('availability_slots')
    op.drop_table('training_plans')
    op.drop_table('members')
    op.drop_table('coaches')
    # ### end Alembic commands ###
