from contextlib import AbstractAsyncContextManager
from typing import Protocol


class ITransactionManager(Protocol):
    def transaction(self, new: bool = False) -> AbstractAsyncContextManager[None]: ...


class ICache(Protocol):
    async def get(self, key: str) -> str | None: ...
    async def set(self, key: str, value: str, ttl_seconds: int) -> None: ...
    async def delete(self, key: str) -> None: ...


class IMessageBroker(Protocol):
    async def publish(self, channel: str, message: str) -> None: ...


class IExerciseClient(Protocol):
    async def get_exercise(self, exercise_id: str) -> dict[str, object] | None: ...
    async def search_exercises(self, name: str) -> list[dict[str, object]]: ...


class IAsyncTaskDispatcher(Protocol):
    async def dispatch(self, task_name: str, /, **kwargs: object) -> None: ...
